# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.19.5'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
NV=np.zeros(10)
NV

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
np.size(NV)

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x=np.arange(1,11)
x[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
ar=[1,2,0,0,4,0] 
idx=np.nonzero(ar)
idx

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
Imtx=np.eye(3,3)
Imtx

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random((3,3,3))

array([[[0.04701267, 0.51225112, 0.2769869 ],
        [0.58131997, 0.66145186, 0.27917987],
        [0.8420352 , 0.51306167, 0.76355295]],

       [[0.65601857, 0.84013581, 0.34468536],
        [0.81287541, 0.67856281, 0.19418997],
        [0.7662799 , 0.4224386 , 0.98853274]],

       [[0.44010036, 0.58793438, 0.33239604],
        [0.98838726, 0.56642699, 0.56619195],
        [0.79248648, 0.75264882, 0.62664471]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
ar=np.random.random((10,10))
x,y=np.min(ar),np.max(ar)
print(ar)
print('min=',x,'max=',y)

[[0.85776242 0.06537881 0.42542726 0.56994339 0.494001   0.92445551
  0.6575317  0.67886375 0.684013   0.90094236]
 [0.19027811 0.63787514 0.40157416 0.79205266 0.08525097 0.14023828
  0.7544354  0.92700108 0.5501176  0.86304341]
 [0.86893422 0.72185164 0.70131438 0.78696758 0.43160239 0.35545844
  0.72818598 0.62011631 0.07379028 0.96762059]
 [0.35152391 0.36934196 0.49593024 0.42033717 0.00394931 0.62661257
  0.68021484 0.47925477 0.56963093 0.62372719]
 [0.49624201 0.66566051 0.88885893 0.88368515 0.28505931 0.71235923
  0.88180178 0.82167916 0.63937472 0.03237263]
 [0.8862563  0.37785442 0.51403407 0.77650578 0.08705761 0.90384128
  0.76848322 0.26020913 0.53484702 0.87931592]
 [0.9669354  0.65723485 0.24249971 0.15386301 0.10648625 0.22788749
  0.61035925 0.06729382 0.34279999 0.30730411]
 [0.74246633 0.57607376 0.48929751 0.78359501 0.5810888  0.78390107
  0.62687903 0.39372867 0.82487883 0.82233911]
 [0.49226186 0.56662516 0.50920985 0.42919385 0.06851799 0.73645808
  0.96242738

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
ar=np.random.random((30))
m=np.mean(ar)
print(ar,'\n','mean=',m)

[0.00580692 0.6486116  0.82706216 0.75485193 0.46500133 0.35177774
 0.66956894 0.72693779 0.26869262 0.9260816  0.06597864 0.85850508
 0.86327815 0.70856357 0.08179832 0.97939714 0.33031196 0.59282439
 0.72314342 0.66450446 0.00981474 0.17945988 0.86106698 0.94255326
 0.35772637 0.19568398 0.95799368 0.16929405 0.12807353 0.98662777] 
 mean= 0.5433663996846309


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
ar=np.ones((6,6))
ar[1:-1,1:-1]=0 #or ar[1:5,1:5]=0 i.e, len-1
print(ar)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
ar=np.ones((5,5))
ar=np.pad(ar,pad_width=1,mode='constant',constant_values=0)
ar

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
l=[]
l.append(0*np.nan)
l.append(np.nan==np.nan)
l.append(np.inf > np.nan)
l.append(np.nan - np.nan)
l.append(0.3==3*0.1)
l

[nan, False, False, nan, False]

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
ar=[1,2,3,4,5]
np.diag(ar)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
ar=np.zeros((8,8),dtype=int)
ar[1::2,::2]=1
ar[::2,1::2]=1
ar

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
arr=np.array([[0,1],[1,0]])
np.tile(arr,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
N = np.random.random((5,5))
Nmax, Nmin = N.max(), N.min()
N= ((N-Nmin)/(Nmax-Nmin))
N

array([[0.30935147, 0.67547543, 0.90820125, 0.15763959, 0.98714076],
       [0.50196583, 0.37950078, 0.92599517, 0.80245439, 0.6212157 ],
       [0.36371723, 0.4627252 , 0.54203458, 0.27547511, 0.1487382 ],
       [0.13161611, 0.09415581, 0.08441485, 0.9106578 , 0.23273651],
       [0.        , 0.74631187, 0.31175595, 0.95046827, 1.        ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
colour = np.dtype([("R", np.ubyte, 1),
                  ("G", np.ubyte, 2),
                  ("B", np.ubyte, 3),
                  ("A", np.ubyte, 4)])
print(colour)

[('R', 'u1'), ('G', 'u1', (2,)), ('B', 'u1', (3,)), ('A', 'u1', (4,))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
Mul= np.dot(np.ones((5,3)), np.ones((3,2)))
Mul

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(1,11)
x[(x > 2) & (x <= 8)] = 0
x

array([ 1,  2,  0,  0,  0,  0,  0,  0,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))#9
from numpy import *
print(sum(range(5),-1))#10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(1,4)
L=[]
L.append(Z**Z)
L.append(2<<Z>>2)
L.append(Z<-Z)
L.append(1j*Z)
L.append(Z/1/1)
# Z<Z>Z this expression is not legal because it throws "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"
L

[array([ 1,  4, 27]),
 array([1, 2, 4]),
 array([False, False, False]),
 array([0.+1.j, 0.+2.j, 0.+3.j]),
 array([1., 2., 3.])]

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))#=nan
print(np.array(0) // np.array(0))#=0
print(np.array([np.nan]).astype(int).astype(float))#=array([-9.22337204e+18])

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = [1.09768,10.8758,15.18762,19.2768,-120.2786]
print(x)
np.copysign(np.ceil(np.abs(x)), x)

[1.09768, 10.8758, 15.18762, 19.2768, -120.2786]


array([   2.,   11.,   16.,   20., -121.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a = np.arange(20, 35)
b = np.arange(25, 40)
print(a,b)
np.intersect1d(a, b)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34] [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all="ignore")
ar = np.ones(1) / 0 #since this is infinity its not recomonded but use of np.seterr will allow it.
ar

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1) #= False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
x = np.datetime64('today', 'D')
y = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
z =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(" Today= ",x,'\n',"Yesterday= ",y,'\n',"Tomorrow= ",z)

 Today=  2022-02-06 
 Yesterday=  2022-02-05 
 Tomorrow=  2022-02-07


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3) * 10
B = np.ones(3) * 20
C = np.ones(3) * 30
print(A,B,C)
print(np.add(A, B, out=B))
print(np.divide(A, 2, out=A))
print(np.negative(A, out=A))
print('((A+B)*(-A/2))=',np.multiply(A, B, out=A))


[10. 10. 10.] [20. 20. 20.] [30. 30. 30.]
[30. 30. 30.]
[5. 5. 5.]
[-5. -5. -5.]
((A+B)*(-A/2))= [-150. -150. -150.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x = np.random.uniform(-5, +5, 10)
print(x)#array
print(x.astype(np.int32))#using astype
print(np.trunc(x))#using trunc
print(np.floor(x))# using floor
print(np.ceil(x)) #using ceil
print(x%x)#using %

[ 1.87126805  4.86122725 -4.55798096 -3.90089801  4.81151889 -0.20781246
  0.48350847 -4.29606394 -4.18423235  2.45328597]
[ 1  4 -4 -3  4  0  0 -4 -4  2]
[ 1.  4. -4. -3.  4. -0.  0. -4. -4.  2.]
[ 1.  4. -5. -4.  4. -1.  0. -5. -5.  2.]
[ 2.  5. -4. -3.  5. -0.  1. -4. -4.  3.]
[ 0.  0. -0. -0.  0. -0.  0. -0. -0.  0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
mtx = np.zeros((5, 5),dtype=int)
mtx += np.arange(5)
mtx

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def gen():
 itr = (x*x for x in range(1,10))
 print(np.fromiter(itr, int))
gen()

[ 1  4  9 16 25 36 49 64 81]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0.1,1,num=10, endpoint=False)

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.uniform(1,7,10)
print(x)
x.sort()
x


[6.10397234 5.97290234 4.68609426 6.7475611  4.29653887 4.39266633
 5.84747303 3.47436593 3.82025719 6.35035601]


array([3.47436593, 3.82025719, 4.29653887, 4.39266633, 4.68609426,
       5.84747303, 5.97290234, 6.10397234, 6.35035601, 6.7475611 ])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

10.10894775390625
8.121967315673828


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.arange(10)
B = np.arange(10)
print(np.allclose(A,B))
print(np.array_equal(A, B))

True
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
ar = np.zeros(10)
ar.flags.writeable = False
#Testing the immutability
ar[0] = 1 # so we cannot edit the array

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.52837078 1.0850681  1.27207962 0.33222758 0.98286308 0.26810854
 0.88090924 0.7864266  0.920239   0.53095276]
[0.70524163 0.59805743 0.74611711 0.4451253  1.45811726 0.10668586
 0.48885145 0.0883238  1.00613475 0.49951184]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
rn = np.random.random(10)
print(rn)
rn[rn.argmax()] = 0
print(rn)

[0.24204699 0.2751713  0.50281888 0.13901305 0.14441807 0.93529235
 0.1416051  0.54640633 0.28879847 0.43114077]
[0.24204699 0.2751713  0.50281888 0.13901305 0.14441807 0.
 0.1416051  0.54640633 0.28879847 0.43114077]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
sa = np.zeros((5,5), [('x',float),('y',float)])
sa['x'], sa['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(sa)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.random.random((5, 5))
Y = np.random.random((5, 5))
c = 1 / (X - Y)
c = 1 / np.subtract.outer(X, Y)
print("The constructed matrix= \n",np.linalg.det(c))

The constructed matrix= 
 [[ 7.10577244e+05  1.71475908e+07 -2.78971666e+05 -1.61918819e+07
  -4.81080987e+04]
 [ 6.92654199e+04 -5.56581359e+04 -5.03278003e+04  7.14800173e+04
  -8.05024660e+04]
 [-8.71576841e+04 -8.11672334e+03 -1.79405611e+05 -1.49192285e+06
  -6.46769139e+04]
 [ 5.92147354e+04  2.03866083e+06 -4.88080785e+04 -5.63589791e+04
  -2.48673336e+05]
 [-2.61574120e+05 -7.56099549e+04 -5.68225553e+04  3.42876426e+06
   1.89585242e+06]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.float32, np.float64]:# for float dtype
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)
for dtype in [np.int8, np.int32, np.int64]:# for integer dtype
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)


-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Alval = np.zeros((25,25))
print(Alval)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
s = np.arange(50)
v = np.random.uniform(0,50)
index = (np.abs(Z-v)).argmin()
print('s=',s,'\n v=',v,'\n the closest value=',s[index])

s= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 
 v= 37.3897587869496 
 the closest value= 9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
sa = np.zeros(10, [ ('position', [ ('x', float, 1),
('y', float, 1)]),
('color', [ ('r', float, 1),
('g', float, 1),
('b', float, 1)])])
sa

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
rv = np.random.random((10,2)) # to see result for 100,2 change 10 to 100
X,Y = np.atleast_2d(rv[:,0]), np.atleast_2d(rv[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(rv,'\n',D)

[[0.45614674 0.6572645 ]
 [0.16274498 0.41751179]
 [0.55699667 0.79310497]
 [0.61388724 0.85376802]
 [0.97782098 0.88809598]
 [0.53910586 0.20715139]
 [0.77680131 0.04680413]
 [0.06803488 0.56880854]
 [0.83504997 0.07483565]
 [0.57184114 0.38557592]] 
 [[0.         0.37890098 0.16918435 0.25198353 0.57046226 0.45769425
  0.68955146 0.39806441 0.69483165 0.29529625]
 [0.37890098 0.         0.54452239 0.62757377 0.94116862 0.43116007
  0.71727913 0.17849569 0.75459985 0.41034079]
 [0.16918435 0.54452239 0.         0.08316575 0.43141209 0.58622665
  0.77799681 0.53795216 0.77021066 0.40779932]
 [0.25198353 0.62757377 0.08316575 0.         0.36554914 0.65092651
  0.82324463 0.61575702 0.80972131 0.47007629]
 [0.57046226 0.94116862 0.43141209 0.36554914 0.         0.81003487
  0.8649745  0.9641863  0.82569724 0.64602325]
 [0.45769425 0.43116007 0.58622665 0.65092651 0.81003487 0.
  0.28672351 0.59388868 0.32417645 0.18140262]
 [0.68955146 0.71727913 0.77799681 0.82324463 0.8649745  0.286723

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
cint = np.arange(10, dtype=np.int32)
cfloat = cint.astype(np.float32, copy=False)
print(cint,cfloat)
# vice-versa
cfloat32 = np.arange(10, dtype=np.float32)
cint32 = cfloat.astype(np.int32, copy=False)
print(cfloat32,cint32)

[0 1 2 3 4 5 6 7 8 9] [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] [0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
miss = StringIO("""1, 2, 3, 4, 5\n6, , , 7, 8\n, , 9,10,11\n""")
out = np.genfromtxt(miss, delimiter=",", dtype=np.int)
print(out)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
nar = np.arange(9).reshape(3,3)
print(nar)
for index, value in np.ndenumerate(nar):
    print(index, value)
for index in np.ndindex(nar.shape):
    print(index, nar[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 5
p = 3
rn = np.zeros((n,n))
np.put(rn, np.random.choice(range(n*n), p, replace=False),1)
print(rn)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 5)
Y = X - X.mean(axis=1, keepdims=True)
print(X,'\n',Y)

[[0.13057374 0.87660585 0.03390944 0.8034976  0.72230451]
 [0.06912744 0.74880247 0.23875602 0.50175965 0.04157593]
 [0.19246104 0.11716341 0.16225943 0.43447624 0.63538264]
 [0.90730459 0.40089124 0.06945711 0.60314882 0.417326  ]
 [0.59986346 0.00489081 0.84316948 0.16343909 0.15765802]] 
 [[-0.38280449  0.36322763 -0.47946879  0.29011938  0.20892628]
 [-0.25087687  0.42879816 -0.08124828  0.18175535 -0.27842837]
 [-0.11588751 -0.19118514 -0.14608913  0.12612769  0.32703408]
 [ 0.42767904 -0.07873431 -0.41016845  0.12352327 -0.06229955]
 [ 0.24605929 -0.34891336  0.48936531 -0.19036508 -0.19614615]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 6 9]
 [3 8 9]
 [9 2 5]]
[[9 2 5]
 [4 6 9]
 [3 8 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
tda = np.random.randint(0,3,(3,10))
print(tda)
print((~tda.any(axis=0)).any())

[[0 0 1 0 0 0 0 2 0 1]
 [2 0 2 0 0 2 0 0 2 1]
 [1 2 2 2 0 0 1 1 1 1]]
True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
arr = np.random.uniform(0,1,10)
val = 0.5
m = arr.flat[np.abs(arr - val).argmin()]
print(m)

0.4138362656064901


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

x = NamedArray(np.arange(10), "10 elements")
y = NamedArray(np.arange(5))
print (x.name,y.name)

10 elements no name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
X = np.ones(10)
I = np.random.randint(0,len(X),20)
print(X,I)
np.add.at(X, I, 1)
print(X)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [1 1 5 7 7 2 5 7 7 7 1 3 0 2 4 4 9 6 8 2]
[2. 4. 4. 2. 3. 3. 2. 6. 2. 2.]


In [ ]:
#or
X += np.bincount(I, minlength=len(X))
print(X)

[ 3.  7.  7.  3.  5.  5.  3. 11.  3.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(F,'\nUnique=',np.unique(I),'number of unique colors=',n)

[[257   0   1 256 257   0 257   1   0 256 256 256 257   1 256   1]
 [  1 256   0 256 257   0 256 256 256 256 256   1   1   0   1 257]
 [  1   0   0   1 257 256   1 257   0 257 256 257   1 256   0 256]
 [256 256   0   0   0 256 256   1 257   1   0   0   1   1   1   0]
 [257   1 256 257 256   0 257   1 257   1 257   1 257   1   1   0]
 [256   0   0   1 256   1   0   0   0 257 256 256 257   0 257 256]
 [  1   1   0   0 257 257 256 257 256   0 257   1   0 257 257 256]
 [257   1 256   1 256   1 257   0   1   1 256   1   0 257 257   1]
 [  0   0 257   0 256   1   0   1   1 256   1 256   0 256 257 256]
 [256 257 256 256 256   0   0 257   1 257 257   1 256   1   1 256]
 [  1   0 257 256 256   0   0 257 257 256   1   1 256   1   1 256]
 [257   1 257   1 256 257   0 256   0   0   0 257   0 256   0   1]
 [256   1   0 256 257 257   0 257 257 257   0   0 256   0 256   0]
 [256   0   1 257   0 257 256 256 257   0   1   0   0 257   1 257]
 [256 256   0   1 257 257   0 257   1 257   0 257   0 256   0 

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[70 75 51 49]
 [67 48 65 60]
 [70 51 53 51]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.40805675 0.51982944 0.53348451 0.42139614 0.51128811 0.50479316
 0.56823042 0.51055835 0.48284321 0.53725888]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
C=np.diag(np.dot(A, B))
print(A,'\n\n',B,'\n\n',C)

[[0.91565823 0.10365403 0.52775991 0.07868288 0.30591147]
 [0.54208162 0.58135854 0.87205347 0.90134436 0.41083717]
 [0.41614542 0.92798639 0.15693854 0.95671363 0.12429936]
 [0.96021698 0.82904851 0.86193672 0.20499475 0.3084928 ]
 [0.0165403  0.40922438 0.29988748 0.92902573 0.03199369]] 

 [[0.18190505 0.37760219 0.8168108  0.5602483  0.33184776]
 [0.3341275  0.72034793 0.70339568 0.39977346 0.96583711]
 [0.89464504 0.17730083 0.60375694 0.86319436 0.97495011]
 [0.49436992 0.83501831 0.24867495 0.74803727 0.89629944]
 [0.11444606 0.65966286 0.41345955 0.07376856 0.39074124]] 

 [0.74726311 1.8017405  1.3767099  1.78951121 1.53829479]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
v1 = np.array([1,2,3,4,5])
nv = 3
v2 = np.zeros(len(v1) + (len(v1)-1)*(nv))
v2[::nv+1] = v1
print(v1,v2)

[1 2 3 4 5] [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
Arr= np.arange(25).reshape(5,5)
print(Arr,"\n\n")
Arr[[0,1]] = Arr[[1,0]]
print(Arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 47) ( 2, 55) ( 4, 83) ( 4, 92) ( 7, 94) ( 7, 98) ( 9, 75) ( 9, 94)
 (21, 25) (21, 40) (21, 73) (25, 73) (33, 81) (33, 91) (39, 62) (39, 85)
 (40, 40) (42, 71) (42, 98) (44, 69) (44, 88) (47, 55) (62, 85) (69, 88)
 (71, 98) (75, 94) (81, 91) (83, 92) (94, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def sliding_window(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(sliding_window(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def one_two(a, window):
    print(a)
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
z=one_two(np.arange(10), 3)
z


[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
arr = np.random.uniform(-1.0,1.0,100)
print(arr)
np.negative(arr, out=arr)

[-7.21152126e-01 -6.96487759e-02  9.91136773e-01  4.09359464e-01
 -2.31478508e-01 -5.21955001e-01  7.37268715e-01 -2.11491415e-01
 -5.82540645e-04 -2.15769934e-01  5.15989600e-01 -8.02335802e-01
  5.81226627e-01 -2.25360913e-01  1.62906488e-01 -9.29592437e-01
 -8.22676905e-02  6.79723260e-02  6.47684700e-01 -5.42633309e-02
 -9.03611778e-01  3.70822990e-01 -2.23361247e-01 -5.68676372e-01
 -9.75127843e-01 -3.67399938e-01 -9.80105554e-01 -8.83433737e-02
 -6.75372130e-01 -3.31294844e-01  4.61911553e-01 -9.04248000e-01
 -4.89003812e-03 -1.51451336e-01  3.15364063e-01  3.14224224e-01
  6.56873627e-01 -7.63113017e-01 -9.22909242e-01 -8.26882205e-01
  8.57840790e-01 -3.30523927e-01  4.80139600e-02  3.43420248e-01
 -1.52699393e-01 -7.98015637e-02 -1.88219829e-01  6.98138153e-01
  1.65070338e-02  9.64404465e-01 -8.97903577e-01  2.54903045e-01
 -3.82855949e-02  7.57811734e-01  1.65956401e-01 -9.72420781e-01
 -2.46722330e-01 -1.43901771e-01  7.79564724e-01  2.28244889e-01
 -8.15490267e-01 -3.46899

array([ 7.21152126e-01,  6.96487759e-02, -9.91136773e-01, -4.09359464e-01,
        2.31478508e-01,  5.21955001e-01, -7.37268715e-01,  2.11491415e-01,
        5.82540645e-04,  2.15769934e-01, -5.15989600e-01,  8.02335802e-01,
       -5.81226627e-01,  2.25360913e-01, -1.62906488e-01,  9.29592437e-01,
        8.22676905e-02, -6.79723260e-02, -6.47684700e-01,  5.42633309e-02,
        9.03611778e-01, -3.70822990e-01,  2.23361247e-01,  5.68676372e-01,
        9.75127843e-01,  3.67399938e-01,  9.80105554e-01,  8.83433737e-02,
        6.75372130e-01,  3.31294844e-01, -4.61911553e-01,  9.04248000e-01,
        4.89003812e-03,  1.51451336e-01, -3.15364063e-01, -3.14224224e-01,
       -6.56873627e-01,  7.63113017e-01,  9.22909242e-01,  8.26882205e-01,
       -8.57840790e-01,  3.30523927e-01, -4.80139600e-02, -3.43420248e-01,
        1.52699393e-01,  7.98015637e-02,  1.88219829e-01, -6.98138153e-01,
       -1.65070338e-02, -9.64404465e-01,  8.97903577e-01, -2.54903045e-01,
        3.82855949e-02, -

In [ ]:
ar = np.random.randint(0,2,100)
np.logical_not(ar, out=ar)

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 7.82587029  2.51493128  3.58806665  6.97467952 11.15072937  9.34124258
  5.29687976  5.76713714  6.3967531   1.95017715]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.18696004  2.07717342  8.90703742 14.83269992  1.74758055]
 [ 6.51323609  2.51899176  6.77759755 12.70361333  1.72010677]
 [ 0.72199067  2.90873667  5.37305598  0.5536547   8.51984054]
 [ 5.64083088  1.69962738  4.98278325 10.90889875  2.69573653]
 [ 0.52294472  2.92759707  9.25983265  3.3326143  13.50086703]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 7 0 4 4 9 1 9 4 6]
 [6 7 5 3 0 1 5 6 5 8]
 [2 5 1 2 8 2 1 1 0 1]
 [0 3 7 8 7 8 9 2 4 5]
 [3 9 3 1 6 2 6 7 3 4]
 [4 2 4 6 2 9 7 8 2 0]
 [7 7 2 6 1 7 3 5 2 4]
 [7 1 8 4 0 9 2 6 1 0]
 [3 3 9 5 8 9 8 2 1 9]
 [9 0 6 7 2 1 1 1 7 4]]
[[0 0 0 0 0]
 [0 6 7 0 4]
 [0 6 7 5 3]
 [0 2 5 1 2]
 [0 0 3 7 8]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 4 3]
   [3 3 1]
   [0 0 1]]

  [[4 3 4]
   [3 1 1]
   [0 1 2]]

  [[3 4 3]
   [1 1 4]
   [1 2 4]]

  [[4 3 2]
   [1 4 1]
   [2 4 3]]

  [[3 2 4]
   [4 1 0]
   [4 3 0]]

  [[2 4 0]
   [1 0 4]
   [3 0 0]]

  [[4 0 4]
   [0 4 1]
   [0 0 3]]

  [[0 4 1]
   [4 1 4]
   [0 3 0]]]


 [[[3 3 1]
   [0 0 1]
   [1 3 1]]

  [[3 1 1]
   [0 1 2]
   [3 1 0]]

  [[1 1 4]
   [1 2 4]
   [1 0 1]]

  [[1 4 1]
   [2 4 3]
   [0 1 0]]

  [[4 1 0]
   [4 3 0]
   [1 0 2]]

  [[1 0 4]
   [3 0 0]
   [0 2 0]]

  [[0 4 1]
   [0 0 3]
   [2 0 3]]

  [[4 1 4]
   [0 3 0]
   [0 3 3]]]


 [[[0 0 1]
   [1 3 1]
   [4 1 0]]

  [[0 1 2]
   [3 1 0]
   [1 0 2]]

  [[1 2 4]
   [1 0 1]
   [0 2 0]]

  [[2 4 3]
   [0 1 0]
   [2 0 4]]

  [[4 3 0]
   [1 0 2]
   [0 4 0]]

  [[3 0 0]
   [0 2 0]
   [4 0 3]]

  [[0 0 3]
   [2 0 3]
   [0 3 3]]

  [[0 3 0]
   [0 3 3]
   [3 3 2]]]


 [[[1 3 1]
   [4 1 0]
   [1 4 4]]

  [[3 1 0]
   [1 0 2]
   [4 4 2]]

  [[1 0 1]
   [0 2 0]
   [4 2 1]]

  [[0 1 0]
   [2 0 4]
   [2 1 4]]

  [[1 0 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4 10 10  6 10]
 [10  3  9  9 14]
 [10  9  3 42  9]
 [ 6  9 42  2  5]
 [10 14  9  5  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def gameoflife(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = gameoflife(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
  1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1
  0 1 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1
  1 1 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
arr = np.arange(1000)
#print(arr)
np.random.shuffle(arr)
n = 10
print (arr[np.argpartition(-arr,n)[:n]])

[995 998 994 993 999 997 996 992 991 990]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
reg = np.array([("Hi", 2.5, 3),("Akash", 5.6, 2)])#regular
rec = np.core.records.fromarrays(reg.T,names='col1, col2, col3',formats = 'S8, f8, i8')#record
print(rec)

[(b'Hi', 2.5, 3) (b'Akash', 5.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))
%timeit a=np.power(x,3)#method-1
%timeit b=x*x*x#method-2
%timeit c=np.einsum('i,i,i->i',x,x,x)#method-3
#print(x,a,b,c)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print('A=',A,'\nB=',B,'\nrows=',rows)

A= [[2 0 4]
 [0 3 2]
 [1 1 4]
 [0 0 0]
 [0 2 4]
 [4 1 1]
 [0 3 4]
 [0 0 3]] 
B= [[2 2]
 [3 2]] 
rows= [0 1 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
arr = np.random.randint(5,10,(10,3))
print(arr)
Eq = np.all(arr[:,1:] == arr[:,:-1], axis=1)
Uneq = arr[~Eq]
print(Uneq)

[[8 8 8]
 [5 9 9]
 [5 5 8]
 [5 6 9]
 [6 5 8]
 [9 8 7]
 [8 6 8]
 [8 6 7]
 [8 5 9]
 [9 5 8]]
[[5 9 9]
 [5 5 8]
 [5 6 9]
 [6 5 8]
 [9 8 7]
 [8 6 8]
 [8 6 7]
 [8 5 9]
 [9 5 8]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(I,B[:,::-1])

[  0   1   2   3  15  16  32  64 128] [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B) 

array([[1.60049058e-02, 7.57387110e-03, 1.10280810e-02, 5.74127674e-03,
        1.94691063e-02, 1.36440054e-02, 2.08889888e-02, 9.09695126e-05,
        5.54211158e-03, 1.12085154e-02],
       [4.86018581e-01, 2.29994611e-01, 3.34888086e-01, 1.74344492e-01,
        5.91215439e-01, 4.14325471e-01, 6.34332797e-01, 2.76245758e-03,
        1.68296473e-01, 3.40367310e-01],
       [1.56060913e-01, 7.38514335e-02, 1.07532803e-01, 5.59821406e-02,
        1.89839699e-01, 1.33040204e-01, 2.03684714e-01, 8.87027099e-04,
        5.40401176e-02, 1.09292186e-01],
       [5.22268788e-01, 2.47149001e-01, 3.59866066e-01, 1.87348159e-01,
        6.35311864e-01, 4.45228372e-01, 6.81645176e-01, 2.96849839e-03,
        1.80849043e-01, 3.65753964e-01],
       [4.56369145e-01, 2.15963850e-01, 3.14458326e-01, 1.63708652e-01,
        5.55148497e-01, 3.89049654e-01, 5.95635492e-01, 2.59393458e-03,
        1.58029591e-01, 3.19603292e-01],
       [3.32921493e-02, 1.57545724e-02, 2.29397488e-02, 1.19425534e-02,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)
print(phi,r_int)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1
 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5
 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3
 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7
 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1
 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5
 19.6 

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17427915  0.20894871]
