In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [1]:
import numpy as np
import pandas as pd



**Step 2: Importing dataset**

In [2]:
df = pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 3: Handling the missing data**

In [3]:
#Delete Row
df1 = pd.read_csv('Data.csv')
df1.isnull().sum().sort_values(ascending=False)
df_no_missing = df1.dropna(axis=0)
print(df_no_missing.head(5))

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes


**Step 4: Encoding categorical data**

In [29]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Country']= label_encoder.fit_transform(df['Country'])
df['Country'].unique()

array([0, 2, 1])

In [30]:
df

Country   Age   Salary Purchased
0        0  44.0  72000.0        No
1        2  27.0  48000.0       Yes
2        1  30.0  54000.0        No
3        2  38.0  61000.0        No
4        1  40.0      NaN       Yes
5        0  35.0  58000.0       Yes
6        2   NaN  52000.0        No
7        0  48.0  79000.0       Yes
8        1  50.0  83000.0        No
9        0  37.0  67000.0       Yes

**Step 5: Creating a dummy variable**

In [31]:
pd.get_dummies(df)

Country   Age   Salary  Purchased_No  Purchased_Yes
0        0  44.0  72000.0             1              0
1        2  27.0  48000.0             0              1
2        1  30.0  54000.0             1              0
3        2  38.0  61000.0             1              0
4        1  40.0      NaN             0              1
5        0  35.0  58000.0             0              1
6        2   NaN  52000.0             1              0
7        0  48.0  79000.0             0              1
8        1  50.0  83000.0             1              0
9        0  37.0  67000.0             0              1

**Step 6: Splitting the datasets into training sets and Test sets**

In [32]:
from sklearn.model_selection import train_test_split
y= df.Purchased
x=df.drop('Purchased',axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x.head()

Country   Age   Salary
0        0  44.0  72000.0
1        2  27.0  48000.0
2        1  30.0  54000.0
3        2  38.0  61000.0
4        1  40.0      NaN

In [33]:
y.head()

0     No
1    Yes
2     No
3     No
4    Yes
Name: Purchased, dtype: object

In [34]:
print("shape of original dataset :", df.shape)
print("shape of input - training set", x_train.shape)
print("shape of output - training set", y_train.shape)
print("shape of input - testing set", x_test.shape)
print("shape of output - testing set", y_test.shape)

shape of original dataset : (10, 4)
shape of input - training set (8, 3)
shape of output - training set (8,)
shape of input - testing set (2, 3)
shape of output - testing set (2,)


**Step 7: Feature Scaling**

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)
X_train

array([[ 0.30151134,  0.40755576,         nan],
       [ 1.50755672,  0.09703708, -0.17298898],
       [-0.90453403, -0.05822225,  0.43247245],
       [ 0.30151134, -1.1450376 , -0.87936065],
       [-0.90453403, -0.36874092, -0.47571969],
       [-0.90453403,  1.64963044,  1.64339531],
       [ 1.50755672, -1.61081561, -1.48482207],
       [-0.90453403,  1.0285931 ,  0.93702364]])

In [38]:
X_test

array([[ 1.50755672,         nan, -1.08118112],
       [ 0.30151134,  1.96014912,  2.04703626]])